server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location = / {
        set $lang en;
        if ($http_accept_language ~* "^de") {
            set $lang de;
        }
        return 302 /$lang/;
    }

    location / {
        try_files $uri $uri/ $uri/index.html =404;
    }
}
