apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/levino/levinkeller.de
  newName: ghcr.io/levino/levinkeller.de
  newTag: 00be95763e00d1bb9ea5c2fa3bf2158151c0a8fd
