apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/levino/levinkeller.de
  newName: ghcr.io/levino/levinkeller.de
  newTag: 2ca042e0fe56b6326c74d78640ff5e4a9809ceaf
