apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/levino/levinkeller.de
  newName: ghcr.io/levino/levinkeller.de
  newTag: b1f66df64576d9d622d4b4d7b5b82a531294432e
